title: MW's amazing site
author: mwolston
email: maran.wolston@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 a site about nothing, really
# social links
github_username:  mwolston # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
